'use strict';

/**
 * Journey catalogue. Every journey feeds both the marketing pages and the
 * booking engine (pricing is derived in pricing.js, never hard-coded here
 * unless `priceFrom` is set purely for display).
 */

const journeys = [
  /* ------------------------------------------------------------------ LUXURY */
  {
    slug: 'starlight-sahara-private-luxury',
    title: 'Starlight Sahara: A Private Luxury Desert Journey',
    type: 'luxury',
    nights: 7,
    minNights: 6,
    maxNights: 14,
    tier: 1,
    lead: 'Seven nights from the Atlantic gate of Marrakech to a private tented city under the Erg Chigaga dunes.',
    summary:
      'This is the journey we are known for: a slow west-to-east arc through four different Moroccos, with two nights in a privately staffed desert camp that moves to follow the moon. Every transfer is in a new-model 4x4 with a driver who has done the road for a decade, and every guide is the one we would hand our own family to.',
    heroImage: '/assets/img/hero-home.jpg',
    gallery: ['/assets/img/desert-camp-luxury.jpg', '/assets/img/riad-courtyard.jpg', '/assets/img/kasbah-sunset.jpg', '/assets/img/atlas-hike.jpg'],
    destinations: ['marrakech', 'high-atlas', 'dades-valley', 'merzouga'],
    feelings: ['wonder', 'solitude', 'restoration'],
    bestMonths: [1, 2, 3, 4, 5, 10, 11, 12],
    maxTravellers: 8,
    pace: 'Gentle — 4 hours of driving on the longest day',
    rating: 4.9,
    reviewCount: 214,
    highlights: [
      'Two nights in a private 6-tent camp deep in Erg Chigaga, reached by camel or 4x4, with a full-time butler, chef and stargazer',
      'Sunrise hot-air balloon over the palm groves of the Haouz plain, breakfast laid in the field afterwards',
      'A closed-after-hours visit to the Saadian Tombs and a conservator-led tour of a family library of manuscripts',
      'Dinner in a Berber family home in the Dadès Valley, cooked with the grandmothers who teach our chefs',
      'A hammam and ghusl ritual designed by a skin therapist, using black soap from the Souss cooperative',
    ],
    itinerary: [
      { day: 1, title: 'Arrival, and the riad that hides a garden', text: 'Met at the aircraft door, driven into the medina to a 17th-century riad. Mint tea on the roof while the muezzin calls across the rooftops; no plans tonight.' },
      { day: 2, title: 'Marrakech, before the souk wakes', text: 'Private 06:40 walk through Jemaa el-Fna as the juice stalls are set out, then the Bahia palace and a conservator-led manuscript room. Afternoon hammam. Balloon briefing at dusk.' },
      { day: 3, title: 'Sunrise flight, then over the Tizi n Tichka', text: 'Balloon at first light with breakfast in the palms. Late drive over the Atlas pass with a stop at the fortified granary of Telouet, and the first view of the rock desert.' },
      { day: 4, title: 'Kasbahs, gorges and the Rose Road', text: 'Ait Ben Haddou at the soft hour, then the Todra gorge on foot with a geologist guide who explains how this wall was sea bed. Overnight in a 12-room kasbah hotel.' },
      { day: 5, title: 'Into the sand', text: 'Drive south through the Draa valley date plantations to the erg edge. Camels carry you the last hour to camp; dinner is one long table in the dunes with Gnawa musicians.' },
      { day: 6, title: 'Nothing, beautifully', text: 'Sunrise walk to a wind-carved ridge. The camp breaks and moves to a new hollow. Midday is for the shade of the tent and a book. Evening: stargazing with a 12-inch Dobsonian and an astronomer from Aloun.' },
      { day: 7, title: 'The long way back via the Draa', text: 'Slow return through the Draa oasis and an unmarked Berber granary few visitors are taken to. Two nights in Marrakech; one final dinner on a terrace we book for you alone.' },
      { day: 8, title: 'Departure, or extend', text: 'Transfer at your pace. Most guests add two nights: Essaouira for fish on the grill, or the Atlas for a valley walk.' },
    ],
    included: [
      'All private transfers in a late-model 4x4 with bottled water and Wi-Fi',
      'Seven nights in riads, kasbah hotels and the private desert camp, breakfast daily',
      'A dedicated licensed guide throughout, plus specialist local guides in each city',
      'Five dinners, including the family dinner and the desert table',
      'Hot-air balloon flight, hammam ritual, camel transfer and stargazing session',
      'Entry fees, reservations and the full 24/7 on-trip line',
    ],
    notIncluded: [
      'International flights (we arrange them at cost, with no ticketing margin)',
      'Lunches, except where a picnic is specified',
      'Personal shopping, though we will book and hold atelier appointments',
    ],
    sampleStays: [
      { name: 'Riad El Fenn-style courtyard riad', place: 'Marrakech medina', note: 'Six rooms, one pool, absolute quiet' },
      { name: 'Kasbah in the Todra gorge', place: 'Tinghir', note: 'Walls built by the family in 1914' },
      { name: 'Private tented camp, six suites', place: 'Erg Chigaga', note: 'Moves to follow the moon; open-air bathroom' },
    ],
    departures: [
      { date: '2026-10-04', status: 'open', note: 'Perfect light, warm sand, cool nights' },
      { date: '2026-11-08', status: 'open', note: 'Best value window of the year' },
      { date: '2027-03-15', status: 'few', note: 'Almond blossom in the Anti-Atlas' },
    ],
    extras: ['hot_air_balloon', 'desert_camp_upgrade', 'hammam_spa', 'photography_guide', 'airport_fast_track', 'carbon_offset', 'domestic_flight'],
    carbonNote: 'Camp runs on solar with a battery bank; we plant 40 native argania seedlings per traveller through the Taroudant cooperative.',
  },
  {
    slug: 'grand-imperial-luxury-circuit',
    title: 'The Grand Imperial Circuit, Done Properly',
    type: 'luxury',
    nights: 10,
    minNights: 9,
    maxNights: 16,
    tier: 1.05,
    lead: 'Marrakech, Essaouira, Casablanca, Rabat, Fez and the Rif — ten nights, four private guides, one unhurried arc.',
    summary:
      'The classic four imperial cities, rebuilt so you never feel like you are ticking them off. You get a different specialist guide in each city, a private sailing morning off Rabat, and the one room in Fez that every photographer asks for.',
    heroImage: '/assets/img/fes-tannery.jpg',
    gallery: ['/assets/img/riad-courtyard.jpg', '/assets/img/marrakech-medina.jpg', '/assets/img/chefchaouen-blue.jpg', '/assets/img/essaouira-coast.jpg'],
    destinations: ['marrakech', 'essaouira', 'casablanca', 'rabat', 'fes', 'chefchaouen'],
    feelings: ['curiosity', 'wonder', 'taste'],
    bestMonths: [3, 4, 5, 6, 9, 10, 11],
    maxTravellers: 10,
    pace: 'Moderate — one long transfer, the rest short',
    rating: 4.9,
    reviewCount: 168,
    highlights: [
      'Private morning on a classic wooden sloop off the Bou Regreg, with oysters landed that hour',
      'A closed-hours viewing of the zellige workshop beneath the Merenid tombs in Chellah',
      'Two nights in Fez with a dedicated medina guide who grew up in the quarter you walk',
      'Lunch on the ramparts at Essaouira eating the day’s catch, chosen by our chef, not the menu',
      'A night in Chefchaouen, the blue town in the Rif, before the day-trippers arrive',
    ],
    itinerary: [
      { day: 1, title: 'Marrakech', text: 'Riad check-in, rooftop dinner, no itinerary. We send you a one-page map of the four corners worth walking tonight.' },
      { day: 2, title: 'Marrakech in depth', text: 'Palaces and the Saadian tombs at opening, then the tanning and dye pits with a conservator. Afternoon free — we will have the hammam booked if you want it.' },
      { day: 3, title: 'To the Atlantic', text: 'Drive to Essaouira through argan forest with a stop at the cooperative. Afternoon on the beach, sunset on the ramparts.' },
      { day: 4, title: 'Atlantic morning, then north', text: 'Private sloop sail at 09:00. Late transfer to Casablanca, Hassan II mosque at golden hour — the only time the Atlantic light works inside.' },
      { day: 5, title: 'Rabat', text: 'The Andalusian gardens, Chellah at closing, and the new royal stables museum with a curator. Overnight facing the river.' },
      { day: 6, title: 'Chefchaouen', text: 'Drive into the Rif. The blue town at dusk is the whole point of tonight; a two-hour guided climb to the Spanish mosque for the view at first light tomorrow.' },
      { day: 7, title: 'To Fez', text: 'Transfer via Meknes, the imperial stables and the mausoleum of Moulay Ismail. Evening in the Qarawiyyin quarter.' },
      { day: 8, title: 'Fez, the working city', text: 'Ceramics in Fès medina’s pottery lane at 07:30, the tanneries from a leather workshop roof, and lunch in a home in the Andalusian quarter.' },
      { day: 9, title: 'Crafts with the makers', text: 'Choose two: zellige cutting, brass engraving, or cedar joinery, each taught by a master with a family workshop you can actually hire through. Gala dinner at Dar Adiyel.' },
      { day: 10, title: 'Farewell', text: 'Early guide, late riad checkout, transfer from Fez airport — or continue to the desert, which most people do.' },
    ],
    included: [
      'Ten nights, breakfast daily and seven dinners',
      'Four specialist city guides plus one driver-guide for the transfers',
      'Private sloop sail, all monument entries and craft sessions with materials',
      'All luggage handling in the medinas — you never carry a bag on cobbles',
    ],
    notIncluded: ['International flights', 'Lunches', 'Spa treatments beyond the included hammam'],
    sampleStays: [
      { name: 'Riad in the Kasbah quarter', place: 'Marrakech', note: 'Twelve rooms, a pool heated in winter' },
      { name: 'House in the Andalusian garden quarter', place: 'Fez', note: 'Courtyard of orange trees and a 14th-century well' },
      { name: 'Rif mountain lodge', place: 'Chefchaouen', note: 'Eighteen terraces, one of which you will not want to leave' },
    ],
    departures: [
      { date: '2026-09-20', status: 'open', note: 'Summer heat broken, sea still warm' },
      { date: '2026-04-12', title: '', note: 'Wildflowers on the Atlantic road' },
    ],
    extras: ['hammam_spa', 'cooking_atelier', 'photography_guide', 'airport_fast_track', 'carbon_offset', 'visa_letter'],
    carbonNote: 'Rail on the Tangier–Fez leg where possible; road transfers consolidated to one vehicle per four guests.',
  },
  {
    slug: 'high-atlas-private-lodge-trail',
    title: 'High Atlas Private Lodge Trail',
    type: 'luxury',
    nights: 8,
    minNights: 7,
    maxNights: 12,
    lead: 'Eight nights of mountain villages, walnut groves and three lodges that took us four years to gather.',
    tier: 0.98,
    summary:
      'Walking is the transport here, or nearly. A support mule carries what you do not want on your back, a chef cooks in villages with no gas line, and you sleep in lodges built and run by the families who own the valley.',
    heroImage: '/assets/img/atlas-hike.jpg',
    gallery: ['/assets/img/kasbah-sunset.jpg', '/assets/img/desert-camp-luxury.jpg', '/assets/img/riad-courtyard.jpg'],
    destinations: ['high-atlas', 'marrakech', 'dades-valley'],
    feelings: ['adventure', 'solitude', 'restoration'],
    bestMonths: [4, 5, 6, 9, 10],
    maxTravellers: 10,
    pace: 'Active — 3 to 5 hours of walking, 450m of ascent on average',
    rating: 4.8,
    reviewCount: 97,
    highlights: [
      'Two nights on the Imlil ridge with a summit option on Toubkal’s lower shoulders at dawn',
      'A mule-supported traverse of four valleys, finishing at a hot spring above Ait Izder',
      'Harvest lunch with an argan cooperative in the Ammeln valley, women only, no cameras without asking',
      'One night of genuine luxury: a 6-room lodge with an outdoor pool cut into the rock, no road access',
    ],
    itinerary: [
      { day: 1, title: 'Up to Imlil', text: 'Ninety minutes from Marrakech. Orientation walk to the shrine, kit check with our mountain lead, dinner with the family who runs the guesthouse.' },
      { day: 2, title: 'The ridge', text: 'Climb to the Sidi Chamarouch shoulder for the first full view of Toubkal. Picnic of amlou and sardine. Two nights in the stone refuge lodge.' },
      { day: 3, title: 'Toubkal dawn, or the easy way', text: 'Optional 04:00 start for the lower summit ridge; a slower alternative walks the mule path with the chef to a watercress valley. Both meet for lunch.' },
      { day: 4, title: 'Down through Azzaden', text: 'Traverse the seven villages of Azzaden, terraces and argan, to the women’s cooperative that supplies the lodges with oil. Bread oven, tea, and an hour of nothing.' },
      { day: 5, title: 'The hot springs', text: 'Long descent to the spring terraces above Ait Izder; swim, then a tagged dinner on the river stones. Mules carry everything.' },
      { day: 6, title: 'Into the Dadès', text: 'Drive east over the skiers’ pass to the roses of Kelaat M’Gouna if the month is right. Evening at the kasbah hotel.' },
      { day: 7, title: 'The lodge with no road', text: 'Transfer to a 4x4 track, a fifteen-minute walk in, and one night of the best bed in Morocco: outdoor pool, no other building in sight.' },
      { day: 8, title: 'Back to the city', text: 'Helicopter return available in place of the three-hour drive, on request and weather permitting. Two Marrakech nights included if you prefer to finish soft.' },
    ],
    included: [
      'Mountain lead, assistant, mule train and cook for the whole traverse',
      'Seven nights: three lodges, two guesthouses, one rock lodge, one kasbah',
      'All breakfasts, lunches (packed) and dinners on the trail',
      'Kit list, boots if you need them, and a physiotherapist on call in Imlil',
    ],
    notIncluded: ['International flights', 'Helicopter transfer (quoted separately)', 'Personal trekking clothing'],
    sampleStays: [
      { name: 'Stone refuge on the Imlil ridge', place: 'Imlil', note: 'Six rooms, wood stoves, blanket on every bed' },
      { name: 'Riverside camp at the springs', place: 'Ait Izder', note: 'Platform tents, hot water pumped from the source' },
      { name: 'No-road rock lodge', place: 'M’Gouna', note: 'Outdoor pool, one table, twelve guests maximum across the valley' },
    ],
    departures: [
      { date: '2026-05-09', status: 'open', note: 'Snow still on the high faces' },
      { date: '2026-09-26', status: 'open', note: 'Harvest in the argan valleys' },
    ],
    extras: ['luggage_logistics', 'hammam_spa', 'desert_camp_upgrade', 'carbon_offset', 'photography_guide'],
    carbonNote: 'Mules rather than vehicles for four of eight days; lodges heated by solar thermal with wood back-up.',
  },
  {
    slug: 'atlantic-riads-private-sailing',
    title: 'Atlantic Riads, Salt and Private Sailing',
    type: 'luxury',
    nights: 7,
    minNights: 6,
    maxNights: 12,
    tier: 1.22,
    lead: 'Marrakech to Essaouira to Imsouane by land, and a private sailing day off the windward coast.',
    summary:
      'For people who want the Morocco of the ocean: fishing ports with nothing to sell you, a wave that breaks for two and a half kilometres, and the riad culture of the south at its most gracious. Luxury here is a table on a beach with no other table.',
    heroImage: '/assets/img/essaouira-coast.jpg',
    gallery: ['/assets/img/riad-courtyard.jpg', '/assets/img/chefchaouen-blue.jpg', '/assets/img/desert-camp-luxury.jpg'],
    destinations: ['essaouira', 'marrakech'],
    feelings: ['restoration', 'solitude', 'taste'],
    bestMonths: [4, 5, 6, 9, 10],
    maxTravellers: 6,
    pace: 'Very gentle — two hours of driving on the longest day',
    rating: 4.9,
    reviewCount: 74,
    highlights: [
      'A full day aboard a private gulet with a chef serving the grill you watched being landed',
      'Sunrise surf lesson at Imsouane on the longest right-hand point break in Africa',
      'A closed-hours private view of the Essaouira wood-and-thuya ateliers with the family that supplies the palaces',
      'Two nights at a dune-front lodge on the road south where the argan trees climb the goats',
    ],
    itinerary: [
      { day: 1, title: 'Marrakech', text: 'Riad, roof dinner, and the only map you need: three streets, one bakery, one courtyard café.' },
      { day: 2, title: 'Down to the wind', text: 'Two hours over the argan plateau to Essaouira. Afternoon in the medina with a woodcarver; sunset on the Skala.' },
      { day: 3, title: 'The boat day', text: 'Private sailing north along the ramparts to a beach with no road. Grilled sea bream, cold Muscat, and a swim in the Atlantic if you are brave.' },
      { day: 4, title: 'Imsouane', text: 'Transfer to the bay. Sunrise in the water with a coach who has surfed it for twenty years; afternoon in the shade with grilled octopus landed at your feet.' },
      { day: 5, title: 'Dunes and goats', text: 'South to a lodge between the ocean and an erg. Sandboard if you like, or a walk the dune line at the last hour.' },
      { day: 6, title: 'North again', text: 'Long coastal drive back to Essaouira with a stop at the Roman ruins of Thamusida. Final dinner in a home kitchen by arrangement.' },
      { day: 7, title: 'Marrakech and out', text: 'Short transfer, late checkout, and one hammam saved for the last morning if you want it.' },
    ],
    included: ['Six nights with breakfast and five dinners', 'Private gulet charter with crew and chef', 'Surf coaching, board and wetsuit', 'All transfers in a private car with a driver who can swim the Atlantic if you ask'],
    notIncluded: ['International flights', 'Lunches', 'Wing or kitesurf instruction (we hold two coaches)'],
    sampleStays: [
      { name: 'Riad facing the port gate', place: 'Essaouira', note: 'Nine rooms, a tile workshop in the courtyard' },
      { name: 'Dune-front lodge', place: 'Taghazout south', note: 'Six suites, outdoor bath, no televisions anywhere' },
    ],
    departures: [{ date: '2026-06-06', status: 'open', note: 'The sea mist keeps it cool' }, { date: '2026-09-12', status: 'few', note: 'Best swell month' }],
    extras: ['hammam_spa', 'photography_guide', 'airport_fast_track', 'carbon_offset', 'cooking_atelier'],
    carbonNote: 'Sailing day under canvas; shore-side logistics run on a single shared vehicle.',
  },

  /* ------------------------------------------------------------------ PRIVATE */
  {
    slug: 'morocco-in-full-private-grand-tour',
    title: 'Morocco in Full: A Private Grand Tour',
    type: 'private',
    nights: 10,
    minNights: 8,
    maxNights: 18,
    tier: 1.1,
    lead: 'The complete arc — ocean, imperial cities, Atlas and Sahara — with one guide who stays with you throughout.',
    summary:
      'Our most-booked private journey, and the one we recommend first if Morocco is new to you and you want it all. Ten nights, one guide, one car, one honest rhythm: mornings for the seeing, afternoons for the being.',
    heroImage: '/assets/img/marrakech-medina.jpg',
    gallery: ['/assets/img/kasbah-sunset.jpg', '/assets/img/fes-tannery.jpg', '/assets/img/riad-courtyard.jpg'],
    destinations: ['marrakech', 'high-atlas', 'dades-valley', 'merzouga', 'fes', 'essaouira'],
    feelings: ['wonder', 'curiosity', 'adventure'],
    bestMonths: [3, 4, 5, 9, 10, 11],
    maxTravellers: 12,
    pace: 'Moderate — one long transfer, the rest short',
    rating: 4.8,
    reviewCount: 502,
    highlights: [
      'One guide for the whole route, chosen for you and sent their profile before you fly',
      'Camel night in the dunes at Merzouga, in a tent with a real bed and a private terrace',
      'The Todra and Dadès gorges on foot, not just through the window',
      'Fes medina at 07:00, before the shutters, with a baker who feeds you on the walk',
    ],
    itinerary: [
      { day: 1, title: 'Marrakech, arrival', text: 'Private transfer, riad, and an easy evening dinner booked at a house in the Kasbah quarter.' },
      { day: 2, title: 'Marrakech, guided', text: 'Palaces, tombs, souk and the spice terrace. Afternoon at the Majorelle garden at the hour the light goes gold.' },
      { day: 3, title: 'Over the Atlas', text: 'Cross the Tichka pass, Ait Ben Haddou at length, and down into the Dadès valley of kasbahs and roses.' },
      { day: 4, title: 'Gorges', text: 'Walk the Todra, then the Tinghir water channel with a local shepherd who keeps the path open.' },
      { day: 5, title: 'To the dunes', text: 'Via Alnif’s Saturday market if the day matches. Camels at the erg edge, dinner with Gnawa drumming, sleep under the sky if you want.' },
      { day: 6, title: 'Dawn and the Ziz', text: 'Sunrise from the high dune, breakfast at camp, then the Ziz valley north with a stop at a Berber fortress museum.' },
      { day: 7, title: 'Ziz to Fes', text: 'Cedar forest and the cedar-bark monkey at Azrou. Evening in Fes with a rooftop over the medina.' },
      { day: 8, title: 'Fes, all day', text: 'The working medina: tannery, potters’ lane, brass, the Qarawiyyin library exterior and the Jewish quarter, with lunch in a home.' },
      { day: 9, title: 'To the coast', text: 'Fast transfer or a short domestic flight to Marrakech, then continue west to Essaouira for the last two nights on the ocean.' },
      { day: 10, title: 'Sea and departure', text: 'Morning on the ramparts, fish grilled at the stall you pointed at, and your flight time handed to the driver.' },
    ],
    included: ['Nine nights in riads and hotels, twin or double, breakfast daily', 'Private air-conditioned vehicle, driver and fuel throughout', 'One licensed private guide for all ten days', 'Eight dinners and the desert camp experience', 'All monument entries on the itinerary'],
    notIncluded: ['International flights', 'Lunches and drinks beyond water', 'Anything you invent along the way — we will price it same-day'],
    sampleStays: [
      { name: 'Riad in the Kasbah quarter', place: 'Marrakech', note: 'Courtyard pool, six rooms' },
      { name: 'Desert camp, Merzouga', place: 'Erg Chebbi', note: 'Private terrace and en-suite; not the shared-camp experience' },
      { name: 'House in the Andalusian quarter', place: 'Fes', note: 'Two suites, one huge cedar terrace' },
    ],
    extras: ['desert_camp_upgrade', 'hot_air_balloon', 'domestic_flight', 'cooking_atelier', 'carbon_offset', 'airport_fast_track'],
    departures: [
      { date: '2026-10-11', status: 'open', note: 'Shoulder pricing, full service' },
      { date: '2026-04-05', status: 'open', note: 'Green Atlas, quiet roads' },
      { date: '2026-12-20', status: 'few', note: 'Christmas departures held until 31 Oct' },
    ],
    rating_note: 'Rated 4.8 from 502 traveller reviews collected after the balance is paid.',
  carbonNote: 'One party, one vehicle, one guide: sharing the transfer that a self-drive would make twice. Where the rail line runs we take the train, and 22 argania seedlings are planted per traveller through the Taroudant cooperative.',
  },
  {
    slug: 'imperial-cities-private-discovery',
    title: 'Imperial Cities: A Private Discovery',
    type: 'private',
    nights: 8,
    minNights: 6,
    maxNights: 12,
    tier: 1,
    lead: 'Rabat, Meknes, Fes and Marrakech in eight unhurried nights, with rail where it is smarter than a car.',
    summary:
      'History-forward and comfortable: the four capitals that built Morocco, in the order that makes sense geographically. Great for first visits, and for anyone who reads the plaques.',
    heroImage: '/assets/img/chefchaouen-blue.jpg',
    gallery: ['/assets/img/fes-tannery.jpg', '/assets/img/marrakech-medina.jpg', '/assets/img/riad-courtyard.jpg'],
    destinations: ['rabat', 'fes', 'marrakech', 'chefchaouen'],
    feelings: ['curiosity', 'connection', 'wonder'],
    bestMonths: [2, 3, 4, 5, 10, 11],
    maxTravellers: 10,
    pace: 'Gentle to moderate — mornings for seeing, afternoons for being',
    rating: 4.8,
    reviewCount: 187,
    highlights: ['Chellah necropolis with an archaeologist, alone at dusk', 'The Alhambra’s sister court at Meknes, restored by a Spanish-Moroccan team', 'Two full nights in Fes rather than a rushed one', 'A museum-of-museums afternoon in Marrakech’s secret palatial house'],
    itinerary: [
      { day: 1, title: 'Rabat', text: 'Arrive by air, meet your guide, and the Andalusian gardens at closing time.' },
      { day: 2, title: 'Rabat and the river', text: 'Chellah with an archaeologist; Hassan tower; the Bou Regreg in the late sun.' },
      { day: 3, title: 'Meknes', text: 'Bab Mansour, the granaries and the mausoleum, then a short drive to Volubilis with the light before it goes.' },
      { day: 4, title: 'Fes', text: 'The medina at full stretch: tannery, potters, the madrasas, Bou Inania’s cedar and zellige. Dinner in a home in the Talaa Kebira.' },
      { day: 5, title: 'Fes, deeper', text: 'Choose: the tanners’ leather atelier for a day, the ceramics kiln, or the Jewish quarter and its museum with a historian.' },
      { day: 6, title: 'To the Middle Atlas', text: 'Cedar forest, Barbary macaques, and an overnight in a hunting lodge above the Ifrane plateau.' },
      { day: 7, title: 'To Marrakech', text: 'Long transfer or a short flight. Evening on the Jemaa el-Fnaa with a guide who will show you which stalls to eat at and which to photograph.' },
      { day: 8, title: 'Marrakech and out', text: 'Bahia, the Saadians, one last souk hour, transfer at your flight time.' },
    ],
    included: ['Seven nights, breakfast daily, three dinners', 'Private car for all overland legs and rail tickets in first class between Rabat and Fes', 'Licensed guides in each city', 'All entries and reservations'],
    notIncluded: ['International flights', 'Lunches', 'Optional domestic flight on day 7 (quoted in your quote tool)'],
    sampleStays: [{ name: 'Riverside hotel in Rabat', place: 'Rabat', note: 'Facing the ocean and the lighthouse' }, { name: 'Riad Fes medina', place: 'Fes', note: 'Eight rooms, a public hammam downstairs' }],
    extras: ['cooking_atelier', 'hammam_spa', 'domestic_flight', 'carbon_offset', 'visa_letter'],
    departures: [{ date: '2026-11-15', status: 'open', note: 'Low season, city prices' }],
  carbonNote: 'Rabat–Fes by first-class rail instead of the road (about 62% less CO2 per traveller), guide-led walking days in all four cities, and no internal flight unless you ask for one.',
  },
  {
    slug: 'marrakech-atlas-foothills',
    title: 'Marrakech and the Atlas Foothills',
    type: 'private',
    nights: 5,
    minNights: 4,
    maxNights: 9,
    tier: 0.95,
    lead: 'A short long-weekender: three nights in a medina riad, two in a valley house an hour up the mountain.',
    summary:
      'The best answer to the question “we have five days and we want to feel Morocco, not see a spreadsheet of it”. No hotel lobby over three floors; no coach parks.',
    heroImage: '/assets/img/riad-courtyard.jpg',
    gallery: ['/assets/img/atlas-hike.jpg', '/assets/img/marrakech-medina.jpg', '/assets/img/kasbah-sunset.jpg'],
    destinations: ['marrakech', 'high-atlas'],
    feelings: ['restoration', 'connection', 'taste'],
    bestMonths: [1, 2, 3, 4, 10, 11, 12],
    maxTravellers: 8,
    pace: 'Easy — nothing starts before 09:30 and no day exceeds three hours in the car',
    rating: 4.7,
    reviewCount: 243,
    highlights: ['Breakfast on a roof with no other guest', 'A half-day argan cooperative lunch where the jam is made in front of you', 'Waterfall walk in Ourika with the valley’s own guide', 'A private dinner cooked by a family chef in a courtyard'],
    itinerary: [
      { day: 1, title: 'Arrive Marrakech', text: 'Transfer in, riad, and an easy walk to the Koutoubia gardens at sunset.' },
      { day: 2, title: 'The city, guided', text: 'Palaces in the morning heat, the souk in the late afternoon when it turns gold, and a food crawl we will happily book for you.' },
      { day: 3, title: 'Into the foothills', text: 'One hour to the Ourika valley. Waterfall walk, Berber lunch, and two nights in a house over the river.' },
      { day: 4, title: 'Valley day', text: 'Choose: a mule path to the seven kasbahs, a cooking morning with the family, or absolutely nothing by the pool.' },
      { day: 5, title: 'Back and out', text: 'Return to Marrakech for one last hammam, then the airport at your time.' },
    ],
    included: ['Four nights, breakfast daily, two dinners', 'Private car and guide for days two and three', 'Argan cooperative visit and valley guide'],
    notIncluded: ['International flights', 'Lunches', 'Anything on the “optional” line'],
    sampleStays: [{ name: 'Riad in the Mouassine quarter', place: 'Marrakech', note: 'Five rooms, one very good cook' }, { name: 'River house', place: 'Ourika', note: 'Open fire, tiles from Tamegroute' }],
    extras: ['hammam_spa', 'cooking_atelier', 'photography_guide', 'airport_fast_track', 'carbon_offset'],
    departures: [{ date: '2026-12-18', status: 'open', note: 'Mild days, cold nights, no crowds' }, { date: '2026-03-06', status: 'open', note: 'Almond blossom' }],
  carbonNote: 'Short transfer distances by design — 90 minutes each way rather than a 580km loop. The valley house heats water with solar thermal and buys its produce within 12km.',
  },
  {
    slug: 'dades-to-dunes-private-self-drive',
    title: 'Dadès to Dunes: Self-Drive with a Safety Net',
    type: 'private',
    nights: 7,
    minNights: 6,
    maxNights: 12,
    tier: 0.85,
    lead: 'You drive. We hold the keys, the rooms, the breakdown recovery and a WhatsApp line that answers in ninety seconds.',
    summary:
      'For travellers who want the road themselves and the certainty of a company behind them. A 4x4 with a roof rack, pre-booked riads, offline maps loaded on your phone, and a support vehicle we keep on standby for the deep-desert days.',
    heroImage: '/assets/img/kasbah-sunset.jpg',
    gallery: ['/assets/img/dades-valley.jpg', '/assets/img/hero-home.jpg', '/assets/img/atlas-hike.jpg'],
    destinations: ['dades-valley', 'merzouga', 'high-atlas'],
    feelings: ['adventure', 'solitude'],
    bestMonths: [3, 4, 5, 10, 11],
    maxTravellers: 8,
    pace: 'You set it — average 3.5 hours of driving, and we will tell you when a day is too long',
    rating: 4.7,
    reviewCount: 129,
    highlights: ['Full insurance, tyre and glass cover, and a satellite messenger in the glovebox', 'Every overnight held in your name with a walk-in contingency for each', 'A printed route book with the fuel stops that actually have fuel', 'Two nights of support: a guide joins for the Chebbi crossing'],
    itinerary: [
      { day: 1, title: 'Collect the car', text: 'Marrakech, at 09:00 with a walk-round you photograph together. Kit, sat-messenger and route book handed over.' },
      { day: 2, title: 'Over the pass', text: 'Tichka to Telouet and Ait Ben Haddou, then up the Dadès valley of a thousand kasbahs.' },
      { day: 3, title: 'The camel roads', text: 'Off-road north to the dunes at Ramlia with a local guide riding point; sleep in a bivouac you reached yourself.' },
      { day: 4, title: 'Chebbi', text: 'Drive the erg edge to Merzouga, meet your guide for the afternoon crossing and a night in a proper tent.' },
      { day: 5, title: 'The oasis road', text: 'East then north through the Ziz valley; short, green, and the best driving day of the trip.' },
      { day: 6, title: 'To Fes', text: 'Ifrane cedar forest, monkeys at the roadside, and an evening in the medina with the car safely locked away.' },
      { day: 7, title: 'Return', text: 'Drive or fly to Casablanca, drop the car, and we take your bags to the check-in desk for you.' },
    ],
    included: ['4x4 with full cover and unlimited mileage', 'Six nights as booked, breakfast daily', 'Satellite messenger and 24-hour recovery', 'Two days with a local off-road guide', 'Route book, offline maps, and fuel-stop list'],
    notIncluded: ['Fuel (about $110 across the trip)', 'International flights and one-way drop fee if not returning to Marrakech', 'Lunches and dinners, except in the desert'],
    sampleStays: [{ name: 'Kasbah hotel', place: 'Boumalne Dadès', note: 'A pool the length of the valley' }, { name: 'Bivouac, Ramlia', place: 'Erg Chebbi south', note: 'Private, staffed, and only by 4x4' }],
    extras: ['4x4_convoy', 'desert_camp_upgrade', 'luggage_logistics', 'carbon_offset', 'visa_letter'],
    departures: [{ date: '2026-04-18', status: 'open', note: 'Warm nights, dry roads' }],
  carbonNote: 'A single 4x4 per party with a load-share policy, fuel use logged per trip and offset through the Atlas Reforestation Fund; the bivouac is pack-in, pack-out.',
  },

  /* ------------------------------------------------------------------ BESPOKE */
  {
    slug: 'the-craft-residency',
    title: 'The Craft Residency: Fes, Safi and the Potters’ Road',
    type: 'bespoke',
    nights: 9,
    minNights: 7,
    maxNights: 21,
    tier: 1.05,
    lead: 'Nine nights living inside Moroccan craft: nine hours a day at the wheel, a master, and a kiln firing at midnight.',
    summary:
      'Built for makers, designers and studios. You are not visiting workshops; you are enrolled in one. We negotiated the access, bought the clay, and pay the masters a teaching rate rather than a tour-guide rate.',
    heroImage: '/assets/img/fes-tannery.jpg',
    gallery: ['/assets/img/riad-courtyard.jpg', '/assets/img/marrakech-medina.jpg', '/assets/img/chefchaouen-blue.jpg'],
    destinations: ['fes', 'marrakech'],
    feelings: ['curiosity', 'connection', 'restoration'],
    bestMonths: [2, 3, 4, 10, 11],
    maxTravellers: 8,
    pace: 'Intense mornings, empty afternoons',
    rating: 5,
    reviewCount: 31,
    highlights: [
      'A private lane in the Fes potters’ quarter, held for you for six days',
      'Green-glaze firing at Tamegroute with the family that still mixes the manganese recipe',
      'A design critique with two Moroccan ceramicists, in Fes, on your own work',
      'Firing day: everyone up at 04:00, everyone paid, no photographs without consent',
    ],
    itinerary: [
      { day: 1, title: 'Arrive Fes, meet the master', text: 'Tea at the workshop, and the week’s schedule pinned up and argued over.' },
      { day: 2, title: 'Clay', text: 'Dig it, wedge it, throw it. Nine hours with two breaks and a lunch nobody leaves.' },
      { day: 3, title: 'Throwing', text: 'More throwing. Then the pattern transfer with the stencil cutters.' },
      { day: 4, title: 'Glaze chemistry', text: 'The cobalt and copper rooms; why Fes blue is not the blue you buy at the souk.' },
      { day: 5, title: 'Bisque and rest', text: 'The kiln is loaded. Afternoon at the Qarawiyyin, evening free.' },
      { day: 6, title: 'To Safi', text: 'Three hours south to the tile and pottery town; the workshops there are bigger and faster.' },
      { day: 7, title: 'Safi, working', text: 'Slipware and zellige cutting; you will cut a panel of twelve and take it home.' },
      { day: 8, title: 'Tamegroute green', text: 'Long drive south-east to the valley of the green glaze; fire at midnight, unload at dawn.' },
      { day: 9, title: 'Show and go', text: 'A small exhibition in the riad courtyard with the masters invited, and freight arranged for what you made.' },
    ],
    included: ['Eight nights, all ceramic materials, tools and firings', 'Master fees at teaching rates, not commission rates', 'All transfers and freight of your work up to 20kg each', 'Interpreter where dialect needs one'],
    notIncluded: ['International flights', 'Excess freight', 'Insurance on your own finished pieces'],
    sampleStays: [{ name: 'Riad with a courtyard kiln', place: 'Fes', note: 'Eight rooms, one of them yours for the whole week' }],
    extras: ['luggage_logistics', 'airport_fast_track', 'carbon_offset', 'visa_letter', 'field_scholar'],
    departures: [{ date: '2026-03-02', status: 'open', note: 'Two places left on the shared residency' }, { date: '2026-10-19', status: 'open', note: 'Private dates available on request' }],
  carbonNote: 'Kilns are wood-fired from pruned olive and palm offcuts, clay is dug within 40km, and your finished work travels as freight rather than as extra checked baggage.',
  },
  {
    slug: 'the-family-reunion',
    title: 'The Family Reunion: One Village, Twelve Nights',
    type: 'bespoke',
    nights: 12,
    minNights: 8,
    maxNights: 24,
    tier: 0.9,
    lead: 'Three generations, one rented village house, and a household staffed so nobody has to organise anything.',
    summary:
      'The most complicated thing we do and the most rewarding. We have run reunions of 8 and of 44 people. What matters is not the riad but the logistics: rooms that suit a grandmother, a babysitter who is not a stranger, and one long table.',
    heroImage: '/assets/img/women-retreat.jpg',
    gallery: ['/assets/img/riad-courtyard.jpg', '/assets/img/kasbah-sunset.jpg', '/assets/img/atlas-hike.jpg'],
    destinations: ['high-atlas', 'marrakech', 'dades-valley', 'essaouira'],
    feelings: ['connection', 'celebration', 'wonder'],
    bestMonths: [5, 6, 7, 8, 9],
    maxTravellers: 44,
    pace: 'Whatever the youngest and oldest need',
    rating: 4.9,
    reviewCount: 46,
    highlights: [
      'Whole-property hire with a housekeeper, two cooks and a night watcher',
      'A day programme that splits by age and rejoins for lunch — kids out with a guide, adults at a cooperative',
      'Step-free rooms, cots, high chairs, a doctor named and briefed before you land',
      'A family book, printed and bound, of photographs from the trip before you fly home',
    ],
    itinerary: [
      { day: 1, title: 'Everyone lands separately', text: 'Nine transfers, one house, and a cold lunch for whoever arrives first.' },
      { day: 2, title: 'The house day', text: 'Pool, gardens, and the long first dinner. Nobody goes anywhere.' },
      { day: 3, title: 'Split', text: 'Kids: mule ride and a picnic. Adults: argan cooperative and a kasbah. Teens: choose both.' },
      { day: 4, title: 'To the mountains', text: 'Half move to a valley lodge; half stay with the grandparents. Same table at eight.' },
      { day: 5, title: 'The workshop day', text: 'Bread, tile-painting, and a kite-making session in the field. Grandparents adjudicate.' },
      { day: 6, title: 'Market morning', text: 'Souk in a small town where nobody is selling you anything, then cooking class with the two chefs.' },
      { day: 7, title: 'The long one', text: 'Optional desert day by 4x4 for the keen; a slow riad day for everyone else.' },
      { day: 8, title: 'Sea', text: 'Two hours to Essaouira; fish on the quay; the kids swim until they cannot feel their toes.' },
      { day: 9, title: 'Back to the house', text: 'A hammam on site and a movie projected on a whitewashed wall.' },
      { day: 10, title: 'Celebration', text: 'Whatever is being marked: a Gnawa troupe, a chef from Marrakech, or a cake in the middle of a courtyard.' },
      { day: 11, title: 'Photograph day', text: 'The family photographer returns for two hours, then the album is assembled while you sleep.' },
      { day: 12, title: 'Departures', text: 'Twelve transfers, staggered. Everyone is given a bag of almonds and a letter.' },
    ],
    included: ['Eleven nights whole-property and block-room hire', 'Household staff for the full stay', 'Four family day programmes with guides', 'All ground transport, including extra airport runs', 'The bound family book'],
    notIncluded: ['International flights (we hold group fares with one booking)', 'Personal spending', 'Any venue rental for a party over 30'],
    sampleStays: [{ name: 'Rented village house with pool', place: 'Haouz plain, 40 min from Marrakech', note: 'Nine bedrooms, four extra tents in the garden' }],
    extras: ['hammam_spa', 'cooking_atelier', 'airport_fast_track', 'carbon_offset', 'camel_caravan', 'luggage_logistics'],
    departures: [{ date: '2026-07-25', status: 'open', note: 'Two weeks held for large families' }],
  carbonNote: 'One household, one kitchen, shared transport for the whole party: eleven travellers in two vehicles rather than eleven rental cars. Food is bought in the souk, not imported.',
  },

  /* -------------------------------------------------------------------- GROUP */
  {
    slug: 'sisters-of-the-medina-and-dunes',
    title: 'Sisters of the Medina & Dunes — Women Only',
    type: 'group',
    audience: 'women',
    nights: 7,
    minNights: 6,
    maxNights: 10,
    tier: 1.05,
    lead: 'Ten to thirty women, an all-female crew on the ground, and the Morocco that opens when the crew is one of you.',
    summary:
      'Guides, drivers, the camp cook and the hammam staff are all women on this departure — not a marketing line but the whole reason the country talks differently to you. Built for best friends, work teams, mother-daughter pairs and solo women travelling together.',
    heroImage: '/assets/img/women-retreat.jpg',
    gallery: ['/assets/img/riad-courtyard.jpg', '/assets/img/hero-home.jpg', '/assets/img/marrakech-medina.jpg'],
    destinations: ['marrakech', 'high-atlas', 'merzouga'],
    feelings: ['connection', 'curiosity', 'celebration'],
    bestMonths: [3, 4, 5, 10, 11],
    groupSizes: [10, 30],
    pace: 'Balanced — two drive days, everything else on foot, and a midday pause in the hot months',
    departureStyle: 'Six fixed departures a year, or private group dates on request',
    rating: 4.9,
    reviewCount: 316,
    highlights: [
      'All-female crew, including two drivers who have run this road for years',
      'A women-only argan cooperative where the meeting is honest because it is private',
      'A female-led desert camp with a sound-healer at sunrise',
      'Two places on every departure held at solidarity rate for a Moroccan women’s association member',
    ],
    itinerary: [
      { day: 1, title: 'Arrive and meet', text: 'Riad, rooftop, an hour of names and no agenda. A welcome pack with the group WhatsApp and what to pack tonight.' },
      { day: 2, title: 'Marrakech, together', text: 'Split into three walks at your own pace, rejoin for the Bahia palace and a long lunch. Evening hammam, booked out.' },
      { day: 3, title: 'The cooperative', text: 'Argan women of the Ammeln valley: cracking, pressing, tasting, and talking about the co-op model. Afternoon to the Atlas foothills.' },
      { day: 4, title: 'Over the pass', text: 'Ait Ben Haddou at length with a historian, then down the Dadès to roses and kasbahs.' },
      { day: 5, title: 'Into the dunes', text: 'Camels at the erg, camp set for women only, sound healing at sunrise tomorrow and a women-led music night.' },
      { day: 6, title: 'Slow return', text: 'Late breakfast, the Draa oasis, and the two-night Marrakech finish.' },
      { day: 7, title: 'Go home different', text: 'Transfers at your flight time, and a group album sent inside a week.' },
    ],
    included: ['Six nights sharing twin rooms; single at supplement', 'Female guide, female drivers and a female group leader per ten travellers', 'Five dinners, hammam session and all entries', 'Solidarity-rate places on request, through the association'],
    notIncluded: ['International flights — group fares released 10 months out', 'Lunches', 'Travel insurance (strongly taken, see booking conditions)'],
    sampleStays: [{ name: 'Women-run riad', place: 'Marrakech', note: 'Owned by its chef; eleven rooms' }, { name: 'Sahara women’s camp', place: 'Erg Chebbi', note: 'Eighteen tents, solar, one long table' }],
    extras: ['hammam_spa', 'desert_camp_upgrade', 'photography_guide', 'camel_caravan', 'carbon_offset'],
    departures: [
      { date: '2026-10-03', status: 'open', note: '22 places taken of 28' },
      { date: '2026-04-11', status: 'few', note: 'Small-group departure, 10–16' },
      { date: '2026-11-14', status: 'waitlist', note: 'Waitlist opens two places at solidarity rate' },
    ],
    carbonNote: 'Two solar camps and one rail leg; group departures average 0.28t CO₂e per traveller overland.',
  carbonNote: 'Two solar camps, one 4x4 per four travellers, and a group size capped at 30 so the medina stays walkable. 40 argania seedlings per traveller, mapped by GPS and audited annually.',
  },
  {
    slug: 'university-field-lab-morocco',
    title: 'Field Lab: Morocco for Universities & Student Groups',
    type: 'group',
    audience: 'students',
    nights: 9,
    minNights: 7,
    maxNights: 14,
    tier: 0.62,
    lead: 'Nine nights, fourteen to thirty students, a resident academic and assessment-grade field logistics.',
    summary:
      'We have run study trips for architecture, hydrology, Arabic, food science and film departments. Everything here exists to make a faculty sign-off easy: risk assessments, safeguarding, chaperone ratios, a 24-hour UK number, and a quote your finance office can actually read.',
    heroImage: '/assets/img/group-students.jpg',
    gallery: ['/assets/img/fes-tannery.jpg', '/assets/img/riad-courtyard.jpg', '/assets/img/atlas-hike.jpg'],
    destinations: ['fes', 'marrakech', 'high-atlas', 'rabat'],
    feelings: ['curiosity', 'adventure', 'connection'],
    bestMonths: [2, 3, 4, 5, 9, 10],
    groupSizes: [14, 30],
    pace: 'Intensive — six hours of field work daily plus evening readings; leaders get the lighter schedule',
    departureStyle: 'Aligned to academic terms; private dates for whole cohorts',
    rating: 4.8,
    reviewCount: 63,
    highlights: [
      'One chaperone or leader free of charge per ten students',
      'Full risk assessment, safeguarding pack and PREVENT-compatible briefing documents',
      'A field notebook, printed, with the sites and questions for your discipline',
      'Budget certainty: 12-month instalment plans and a fixed-price guarantee from 210 days out',
    ],
    itinerary: [
      { day: 1, title: 'Land, brief, base', text: 'Arrivals at Fes, orientation on the medina’s street logic, and the first field-methods session in the courtyard.' },
      { day: 2, title: 'Water', text: 'The traditional sabbat water channels and the ceramic cistern makers; a measurement exercise for hydrology groups.' },
      { day: 3, title: 'Craft and economics', text: 'Tannery and brass: interview a master, then model the margin on a finished bag. Data collected, arguments started.' },
      { day: 4, title: 'To the Middle Atlas', text: 'Cedar forest ecology transects and the macaque population study at Azrou; overnight in a student-friendly lodge.' },
      { day: 5, title: 'Ozoud', text: 'The wetlands of Lake Oulmi: a bird and reed survey, and a session with the reserve warden.' },
      { day: 6, title: 'Marrakech: urbanism', text: 'Douar Sabbagh’s self-built quarter, medina regeneration and the riad-restoration economy. Sketching night.' },
      { day: 7, title: 'Atlas', text: 'Terracing and argan agroforestry with a farmer cooperative; two hours of actual work in the groves.' },
      { day: 8, title: 'Synthesis', text: 'Groups prepare a twenty-minute presentation to the cohort and one Moroccan academic guest; dinner after.' },
      { day: 9, title: 'Fly', text: 'Transfers from Marrakech, and the reference pack and photos released to your department within a week.' },
    ],
    included: ['Eight nights in twin and quad rooms, breakfast and five dinners', 'Private coach, driver, mechanic and two leaders', 'Resident academic liaison for the week', 'Risk assessment, safeguarding and finance-office documentation', 'Field notebooks and printing'],
    notIncluded: ['International flights (we hold block seats for cohorts over 20)', 'Lunches — packed and cheap, or arranged', 'Personal spending'],
    sampleStays: [{ name: 'Cedar lodge', place: 'Azrou', note: 'Group dorm annex plus twins; WiFi in the common room' }, { name: 'Student house', place: 'Marrakech', note: 'Twenty-two beds, a courtyard and a very early curfew if you want one' }],
    extras: ['field_scholar', 'luggage_logistics', 'carbon_offset', 'visa_letter', 'airport_fast_track'],
    departures: [
      { date: '2026-02-21', status: 'open', note: 'Spring term cohort window' },
      { date: '2026-09-26', status: 'open', note: 'Autumn cohort, 24 places held for one department' },
    ],
    carbonNote: 'Coach over rail is avoided; group coach replaced by two trains where the line runs, saving about 60% of transport CO₂.',
  carbonNote: 'Trains replace coaches on the Rabat–Fes leg, one coach per 15 students where rail does not run, and field-day travel is walked or mule-supported. Printed packs, no plastic lanyards.',
  },
  {
    slug: 'slow-morocco-seniors-grand-journey',
    title: 'Slow Morocco: The Seniors’ Grand Journey',
    type: 'group',
    audience: 'seniors',
    nights: 9,
    minNights: 8,
    maxNights: 12,
    tier: 0.95,
    lead: 'Nine nights for travellers aged 60 and over: no 6am starts, no standing for two hours, and a doctor on call.',
    summary:
      'The grand tour, redesigned around how people actually want to travel later in life. Shorter transfers, step-free rooms confirmed in writing, one guide who never rushes, and the pace where you can still notice things.',
    heroImage: '/assets/img/seniors-garden.jpg',
    gallery: ['/assets/img/riad-courtyard.jpg', '/assets/img/marrakech-medina.jpg', '/assets/img/kasbah-sunset.jpg'],
    destinations: ['marrakech', 'essaouira', 'fes', 'dades-valley', 'rabat'],
    feelings: ['curiosity', 'connection', 'restoration'],
    bestMonths: [3, 4, 5, 9, 10, 11],
    groupSizes: [10, 24],
    pace: 'Slow — transfers capped at three hours, nothing before 09:30, midday rest written into the plan',
    departureStyle: 'Four fixed departures a year',
    rating: 4.9,
    reviewCount: 201,
    highlights: [
      'Transfers capped at three hours, with a proper stop every ninety minutes',
      'Step-free or lift access at every property, confirmed before you pay',
      'A named doctor on call in each city, plus a first-aid qualified leader per ten travellers',
      'Reading glasses, magnifier and a large-print itinerary in every pack',
    ],
    itinerary: [
      { day: 1, title: 'Marrakech at leisure', text: 'Transfer whenever you land; tea and a short guided orientation only if you feel like it.' },
      { day: 2, title: 'Marrakech', text: 'The palaces in the cool morning, rest through the middle of the day, and a souk stroll in the gold evening light.' },
      { day: 3, title: 'Gardens and the ocean', text: 'Majorelle and Le Jardin Secret, then a slow drive to Essaouira with one long stop at the argan cooperative.' },
      { day: 4, title: 'Essaouira', text: 'The ramparts, an art gallery run by a local family, and fish on the quay. Nothing else.' },
      { day: 5, title: 'To the Kasbah country', text: 'Longer transfer, two rest stops, and arrival in time for a valley walk of forty minutes if the legs want it.' },
      { day: 6, title: 'The Dadès', text: 'Rose distilleries, the valley of a thousand kasbahs, and a seated history talk under a walnut tree.' },
      { day: 7, title: 'To Fes', text: 'Fly from Ouarzazate rather than drive, at no extra cost on this departure — a deliberate choice for the knees and backs.' },
      { day: 8, title: 'Fes', text: 'Slow guided morning, wheelchair-accessible medina route available on request, and a ceramics session you watch from a shaded terrace.' },
      { day: 9, title: 'Home', text: 'Late riad checkout, transfer at flight time, and a courtesy call to a family contact if you asked us to.' },
    ],
    included: ['Eight nights in hand-picked step-friendly properties, breakfast daily, six dinners', 'Small-group coach with two leaders and a first-aid qualified guide', 'Domestic flight Ouarzazate–Fes on the standard itinerary', 'All entries, and a large-print daily plan each morning'],
    notIncluded: ['International flights', 'Lunches', 'Travel insurance if you bring your own'],
    sampleStays: [{ name: 'Riad with lift', place: 'Marrakech', note: 'Ground-floor suites with walk-in showers' }, { name: 'Garden hotel', place: 'Fes', note: 'No stairs to your room, ever' }],
    extras: ['wellness_kit', 'hammam_spa', 'airport_fast_track', 'carbon_offset', 'visa_letter', 'cooking_atelier'],
    departures: [
      { date: '2026-04-14', status: 'open', note: 'Six places left' },
      { date: '2026-10-06', status: 'open', note: 'Our most popular departure' },
    ],
    carbonNote: 'One internal flight on a route where driving is disproportionate; the remainder is coach and rail.',
  carbonNote: 'One short domestic flight where a five-hour coach day would be worse for the group and only marginally better for the planet; everything else is coach and rail with two leaders sharing a vehicle.',
  },
  {
    slug: 'desert-wellness-retreat-for-women',
    title: 'Desert Wellness Retreat for Women',
    type: 'group',
    audience: 'women',
    nights: 6,
    minNights: 5,
    maxNights: 8,
    tier: 1.12,
    lead: 'Six nights of breathwork, hammam and silence between the Atlas and the first dunes — women only, twelve to twenty places.',
    summary:
      'Small by design: twelve travellers, one teacher, and a schedule with holes in it on purpose. Two days of gentle walking, one day of complete rest, and a desert night under the sky instead of a spa.',
    heroImage: '/assets/img/desert-camp-luxury.jpg',
    gallery: ['/assets/img/luxury-pool.jpg', '/assets/img/riad-courtyard.jpg', '/assets/img/kasbah-sunset.jpg'],
    destinations: ['high-atlas', 'dades-valley', 'merzouga'],
    feelings: ['restoration', 'solitude', 'connection'],
    bestMonths: [2, 3, 4, 10, 11, 12],
    groupSizes: [10, 20],
    pace: 'Restorative — one practice at dawn, then nothing scheduled until the evening circle',
    departureStyle: 'Three departures a year, plus private group dates',
    rating: 5,
    reviewCount: 58,
    highlights: ['Sunset breathwork on a dune ridge with a teacher who has done this for twelve years', 'A full silent day, and a facilitated sharing circle that evening', 'Two hammam and ghillor rituals with a therapist who travels with the group', 'Journaling pack and an optional one-to-one session before you fly'],
    itinerary: [
      { day: 1, title: 'Arrive, down-shift', text: 'Marrakech riad, an hour of yoga on the roof, and no phones after dinner.' },
      { day: 2, title: 'Into the mountains', text: 'Walk the Ourika terraces; afternoon treatment on a shaded terrace; evening sound bath.' },
      { day: 3, title: 'The silent day', text: 'One guided practice at dawn, then nothing scheduled until the sharing circle at dusk.' },
      { day: 4, title: 'To the dunes', text: 'Drive east; camels in; a night in a women-led camp with one long table and no music.' },
      { day: 5, title: 'Sunrise and the return', text: 'Breathwork on the ridge at first light, then home via the Draa oasis for lunch.' },
      { day: 6, title: 'Marrakech, gently', text: 'A final hammam and a transfer at your flight time; integration notes sent a week later.' },
    ],
    included: ['Five nights, all breakfasts and five dinners', 'Resident teacher and therapist for the whole retreat', 'All walks, camp, entries and transfers', 'Journal pack, mat, block and bolsters provided'],
    notIncluded: ['International flights', 'Lunches', 'One-to-one sessions beyond the one included'],
    sampleStays: [{ name: 'Women-led mountain house', place: 'Ourika', note: 'Nine rooms, one heated pool, no road noise' }, { name: 'Silent desert camp', place: 'Erg Chebbi west', note: 'Twelve tents, solar only, no generator' }],
    extras: ['hammam_spa', 'desert_camp_upgrade', 'wellness_kit', 'carbon_offset'],
    departures: [{ date: '2026-11-09', status: 'open', note: 'Eight places' }, { date: '2027-02-15', status: 'open', note: 'Early-bird pricing until 30 Nov' }],
    carbonNote: 'Camp is solar, transfers are shared at a ratio of one 4x4 per four travellers.',
  carbonNote: 'Silent solar camp with no generator after 22:00, one 4x4 per four travellers, and a 20-place cap that keeps the group under the size the valley paths can absorb.',
  },
];

/** Convenience for the group-tour landing page. */
const groupAudiences = {
  women: {
    key: 'women',
    name: 'Women-only group departures',
    strapline: 'Every guide, driver, cook and camp host on these journeys is a woman.',
    copy:
      'We started these departures in 2016 after a request from a Moroccan women’s association who wanted to show their own country to visitors without the male intermediary. They now run six times a year. Two places on every departure are held at solidarity rate for a member of a Moroccan cooperative, allocated by the association, not by us.',
    includes: [
      'Female licensed guides and drivers throughout',
      'Women-only riads, hammam sessions and a women-led desert camp',
      'Private cooperative visits where the conversation is honest',
      'A group leader for every ten travellers, and a 24-hour line',
    ],
    suitability: 'Best for friends, teams, mother-daughter travel and solo women travelling in a group. 10 to 30 places.',
  },
  students: {
    key: 'students',
    name: 'Student & university groups',
    strapline: 'Academic logistics, safeguarding paperwork and a price your finance office will approve.',
    copy:
      'Departures are built around a discipline — hydrology, architecture, Arabic, food science, film, anthropology — and staffed with a resident academic liaison plus one free leader place for every ten students. We hold block airline seats for cohorts over twenty and can invoice in USD, GBP, EUR or MAD.',
    includes: [
      'Risk assessments, safeguarding pack and chaperone ratios',
      'Field notebook printed with your syllabus sites and questions',
      'One leader free of charge per ten full-paying students',
      '12-month instalment plans and fixed pricing from 210 days out',
    ],
    suitability: 'Higher and further education groups, 14 to 30 students, timed to term calendars.',
  },
  seniors: {
    key: 'seniors',
    name: 'Senior group journeys, 60+',
    strapline: 'Three-hour transfer cap, step-free rooms confirmed in writing, and nobody rushed.',
    copy:
      'The grand tour at a humane pace, with a first-aid qualified leader, a named doctor on call in each city, and one internal flight on the route where driving would be unreasonable. Groups of 10 to 24, four departures a year, and a courtesy call to a family member on request.',
    includes: [
      'Step-free or lift-accessible rooms at every property, confirmed pre-payment',
      'Transfers of no more than three hours with stops every ninety minutes',
      'Large-print daily plans, and magnifiers and reading glasses in the pack',
      'A first-aid qualified leader for every ten travellers',
    ],
    suitability: 'Groups of 10 to 24; solo travellers welcome and matched to a same-sex roommate at no surcharge.',
  },
};

module.exports = { journeys, groupAudiences };
